#!/bin/sh
repl=$(grep "<li>" "$HOME/documents/main/blogindex.html" | sed 5q | tr -d '\n' | sed -e 's/[\/&]/\\&/g')
sed -i "s/<!--BLOG-->.*/<!--BLOG-->$repl/g" ~/documents/main/index.html

rsync -avrP --delete-after --rsh='ssh' ~/documents/main/ root@akiranakano.info:/var/www/main/
